#+title: Mark
#+HTML: <h1> The Gospel According to <br> M A R K </h1>
#+setupfile: ../setup/bible.setup

** Mark 1
*** The Mission of John the Baptist (Luke 3:1--22; John 1:19--34)
[[html-class:drop][1]]


<<1:1>> This is the beginning of the gospel of Jesus Christ, the Son of God. 
<<1:2>> *2* As it is written in Isaiah the prophet:

“Behold, I will send My messenger ahead of You,

who will prepare Your way.”

<<1:3>> *3* “A voice of one calling in the wilderness,

‘Prepare the way for the Lord,

make straight paths for Him.' ”

<<1:4>> *4* John the Baptist appeared in the wilderness, preaching a baptism of repentance for the forgiveness of sins. 
<<1:5>> *5* People went out to him from all of Jerusalem and the countryside of Judea. Confessing their sins, they were baptized by him in the Jordan River.

<<1:6>> *6* John was clothed in camel's hair, with a leather belt around his waist. His food was locusts and wild honey. 
<<1:7>> *7* And he began to proclaim: “After me will come One more powerful than I, the straps of whose sandals I am not worthy to stoop down and untie. 
<<1:8>> *8* I baptize you with water, but He will baptize you with the Holy Spirit.”

<<1:9>> *9* In those days Jesus came from Nazareth in Galilee and was baptized by John in the Jordan. 
<<1:10>> *10* As soon as Jesus came up out of the water, He saw the heavens breaking open and the Spirit descending on Him like a dove. 
<<1:11>> *11* And a voice came from heaven: “You are My beloved Son; in You I am well pleased.”

*** The Temptation and Preaching of Jesus (Matthew 4:1--17; Luke 4:1--15)

<<1:12>> *12* At once the Spirit drove Jesus into the wilderness, 
<<1:13>> *13* and He was there for forty days, being tempted by Satan. He was with the wild animals, and the angels ministered to Him.

<<1:14>> *14* After the arrest of John, Jesus went into Galilee and proclaimed the gospel of God.
<<1:15>> *15* “The time is fulfilled,” He said, “and the kingdom of God is near. Repent and believe in the gospel!”

*** The First Disciples (Luke 5:1--11; John 1:35--42)

<<1:16>> *16* As Jesus was walking beside the Sea of Galilee, He saw Simon and his brother Andrew. They were casting a net into the sea, for they were fishermen.
<<1:17>> *17* “Come, follow Me,” Jesus said, “and I will make you fishers of men.” 
<<1:18>> *18* And at once they left their nets and followed Him.

<<1:19>> *19* Going on a little farther, He saw James son of Zebedee and his brother John. They were in a boat, mending their nets. 
<<1:20>> *20* Immediately Jesus called them, and they left their father Zebedee in the boat with the hired men and followed Him.

*** Jesus Expels an Unclean Spirit (Luke 4:31--37)

<<1:21>> *21* Then Jesus and His companions went to Capernaum, and right away Jesus entered the synagogue on the Sabbath and began to teach. 
<<1:22>> *22* The people were astonished at His teaching, because He taught as one who had authority, and not as the scribes.

<<1:23>> *23* Suddenly a man with an unclean spirit cried out in the synagogue:
<<1:24>> *24* “What do You want with us, Jesus of Nazareth? Have You come to destroy us? I know who You are---the Holy One of God!”

<<1:25>> *25* But Jesus rebuked the spirit. “Be silent!” He said. “Come out of him!” 
<<1:26>> *26* At this, the unclean spirit threw the man into convulsions and came out with a loud shriek.

<<1:27>> *27* All the people were amazed and began to ask one another, “What is this? A new teaching with authority! He commands even the unclean spirits, and they obey Him!” 
<<1:28>> *28* And the news about Jesus spread quickly through the whole region of Galilee.

*** Jesus Heals at Peter's House (Matthew 8:14--17; Luke 4:38--41)

<<1:29>> *29* As soon as Jesus and His companions had left the synagogue, they went with James and John to the home of Simon and Andrew. 
<<1:30>> *30* Simon's mother-in-law was sick in bed with a fever, and they promptly told Jesus about her. 
<<1:31>> *31* So He went to her, took her by the hand, and helped her up. The fever left her, and she began to serve them.

<<1:32>> *32* That evening, after sunset, people brought to Jesus all who were sick and demon-possessed, 
<<1:33>> *33* and the whole town gathered at the door. 
<<1:34>> *34* And He healed many who were ill with various diseases and drove out many demons. But He would not allow the demons to speak, because they knew who He was.

*** Jesus Prays and Preaches (Luke 4:42--44)

<<1:35>> *35* Early in the morning, while it was still dark, Jesus got up and slipped out to a solitary place to pray. 
<<1:36>> *36* Simon and his companions went to look for Him, 
<<1:37>> *37* and when they found Him, they said, “Everyone is looking for You!”

<<1:38>> *38* But Jesus answered, “Let us go on to the neighboring towns so I can preach there as well, for that is why I have come.” 
<<1:39>> *39* So He went throughout Galilee, preaching in their synagogues and driving out demons.

*** The Leper's Prayer (Matthew 8:1--4; Luke 5:12--16)

<<1:40>> *40* Then a leper came to Jesus, begging on his knees: “If You are willing, You can make me clean.”

<<1:41>> *41* Moved with compassion, Jesus reached out His hand and touched the man. “I am willing,” He said. “Be clean!” 
<<1:42>> *42* And immediately the leprosy left him, and the man was cleansed.

<<1:43>> *43* Jesus promptly sent him away with a stern warning:
<<1:44>> *44* “See that you don't tell anyone. But go, show yourself to the priest and present the offering Moses prescribed for your cleansing, as a testimony to them.”

<<1:45>> *45* But the man went out and openly began to proclaim and spread the news.

Consequently, Jesus could no longer enter a town in plain view, but He stayed out in solitary places. Yet people came to Him from every quarter.

** Mark 2
*** Jesus Heals a Paralytic (Matthew 9:1--8; Luke 5:17--26)
[[html-class:drop][2]]

<<2:1>> A few days later Jesus went back to Capernaum. And when the people heard that He was home, 
<<2:2>> *2* they gathered in such large numbers that there was no more room, not even outside the door, as Jesus spoke the word to them.

<<2:3>> *3* Then a paralytic was brought to Him, carried by four men. 
<<2:4>> *4* Since they were unable to get to Jesus through the crowd, they uncovered the roof above Him, made an opening, and lowered the paralytic on his mat.

<<2:5>> *5* When Jesus saw their faith, He said to the paralytic, “Son, your sins are forgiven.”

<<2:6>> *6* But some of the scribes were sitting there and thinking in their hearts,
<<2:7>> *7* “Why does this man speak like this? He is blaspheming! Who can forgive sins but God alone?”

<<2:8>> *8* At once Jesus knew in His spirit that they were thinking this way within themselves. “Why are you thinking these things in your hearts?” He asked.
<<2:9>> *9* “Which is easier: to say to a paralytic, ‘Your sins are forgiven,' or to say, ‘Get up, pick up your mat, and walk'? 
<<2:10>> *10* But so that you may know that the Son of Man has authority on earth to forgive sins...” He said to the paralytic,
<<2:11>> *11* “I tell you, get up, pick up your mat, and go home.”

<<2:12>> *12* And immediately the man got up, picked up his mat, and walked out in front of them all. As a result, they were all astounded and glorified God, saying, “We have never seen anything like this!”

*** Jesus Calls Levi (Matthew 9:9--13; Luke 5:27--32)

<<2:13>> *13* Once again Jesus went out beside the sea. All the people came to Him, and He taught them there.

<<2:14>> *14* As He was walking along, He saw Levi son of Alphaeus sitting at the tax booth. “Follow Me,” He told him, and Levi got up and followed Him.

<<2:15>> *15* While Jesus was dining at Levi's house, many tax collectors and sinners were eating with Him and His disciples---for there were many who followed Him. 
<<2:16>> *16* When the scribes who were Pharisees saw Jesus eating with these people, they asked His disciples, “Why does He eat with tax collectors and sinners?”

<<2:17>> *17* On hearing this, Jesus told them, “It is not the healthy who need a doctor, but the sick. I have not come to call the righteous, but sinners.”

*** Questions about Fasting (Matthew 9:14--15; Luke 5:33--35)

<<2:18>> *18* Now John's disciples and the Pharisees were often fasting. So people came to Jesus and asked, “Why don't Your disciples fast like John's disciples and those of the Pharisees?”

<<2:19>> *19* Jesus replied, “How can the guests of the bridegroom fast while He is with them? As long as He is with them, they cannot fast. 
<<2:20>> *20* But the time will come when the bridegroom will be taken from them; then they will fast.

*** The Patches and the Wineskins (Matthew 9:16--17; Luke 5:36--39)

<<2:21>> *21* No one sews a patch of unshrunk cloth on an old garment. If he does, the new piece will pull away from the old, and a worse tear will result.

<<2:22>> *22* And no one pours new wine into old wineskins. If he does, the wine will burst the skins, and both the wine and the wineskins will be ruined. Instead, new wine is poured into new wineskins.”

*** The Lord of the Sabbath (Matthew 12:1--8; Luke 6:1--5)

<<2:23>> *23* One Sabbath Jesus was passing through the grainfields, and His disciples began to pick the heads of grain as they walked along. 
<<2:24>> *24* So the Pharisees said to Him, “Look, why are they doing what is unlawful on the Sabbath?”

<<2:25>> *25* Jesus replied, “Have you never read what David did when he and his companions were hungry and in need? 
<<2:26>> *26* During the high priesthood of Abiathar, he entered the house of God and ate the consecrated bread, which was lawful only for the priests. And he gave some to his companions as well.”

<<2:27>> *27* Then Jesus declared, “The Sabbath was made for man, not man for the Sabbath. 
<<2:28>> *28* Therefore, the Son of Man is Lord even of the Sabbath.”

** Mark 3
*** Jesus Heals on the Sabbath (Matthew 12:9--14; Luke 6:6--11)
[[html-class:drop][3]]

<<3:1>> Once again Jesus entered the synagogue, and a man with a withered hand was there. 
<<3:2>> *2* In order to accuse Jesus, they were watching to see if He would heal on the Sabbath.

<<3:3>> *3* Then Jesus said to the man with the withered hand, “Stand up among us.” 
<<3:4>> *4* And He asked them, “Which is lawful on the Sabbath: to do good or to do evil, to save life or to destroy it?”

But they were silent.

<<3:5>> *5* Jesus looked around at them with anger and sorrow at their hardness of heart. Then He said to the man, “Stretch out your hand.” So he stretched it out, and it was restored.

<<3:6>> *6* At this, the Pharisees went out and began plotting with the Herodians how they might kill Jesus.

*** Jesus Heals the Multitudes (Matthew 4:23--25; Luke 6:17--19)

<<3:7>> *7* So Jesus withdrew with His disciples to the sea, accompanied by a large crowd from Galilee, Judea, 
<<3:8>> *8* Jerusalem, Idumea, the region beyond the Jordan, and the vicinity of Tyre and Sidon. The large crowd came to Him when they heard what great things He was doing.

<<3:9>> *9* Jesus asked His disciples to have a boat ready for Him so that the crowd would not crush Him. 
<<3:10>> *10* For He had healed so many that all who had diseases were pressing forward to touch Him. 
<<3:11>> *11* And when the unclean spirits saw Him, they fell down before Him and cried out, “You are the Son of God!” 
<<3:12>> *12* But He warned them sternly not to make Him known.

*** The Twelve Apostles (Matthew 10:1--4; Luke 6:12--16)

<<3:13>> *13* Then Jesus went up on the mountain and called for those He wanted, and they came to Him. 
<<3:14>> *14* He appointed twelve of them, whom He designated as apostles, to accompany Him, to be sent out to preach, 
<<3:15>> *15* and to have authority to drive out demons.

<<3:16>> *16* These are the twelve He appointed: Simon (whom He named Peter), 
<<3:17>> *17* James son of Zebedee and his brother John (whom He named Boanerges, meaning “Sons of Thunder”), 
<<3:18>> *18* Andrew, Philip, Bartholomew, Matthew, Thomas, James son of Alphaeus, Thaddaeus, Simon the Zealot, 
<<3:19>> *19* and Judas Iscariot, who betrayed Jesus.

*** A House Divided (Matthew 12:22--30; Luke 11:14--23)

<<3:20>> *20* Then Jesus went home, and once again a crowd gathered, so that He and His disciples could not even eat. 
<<3:21>> *21* When His family heard about this, they went out to take custody of Him, saying, “He is out of His mind.”

<<3:22>> *22* And the scribes who had come down from Jerusalem were saying, “He is possessed by Beelzebul,” and, “By the prince of the demons He drives out demons.”

<<3:23>> *23* So Jesus called them together and began to speak to them in parables: “How can Satan drive out Satan? 
<<3:24>> *24* If a kingdom is divided against itself, it cannot stand. 
<<3:25>> *25* If a house is divided against itself, it cannot stand. 
<<3:26>> *26* And if Satan is divided and rises against himself, he cannot stand; his end has come. 
<<3:27>> *27* Indeed, no one can enter a strong man's house to steal his possessions unless he first ties up the strong man. Then he can plunder his house.

*** The Unpardonable Sin (Matthew 12:31--32)

<<3:28>> *28* Truly I tell you, the sons of men will be forgiven all sins and blasphemies, as many as they utter. 
<<3:29>> *29* But whoever blasphemes against the Holy Spirit will never be forgiven; he is guilty of eternal sin.”

<<3:30>> *30* Jesus made this statement because they were saying, “He has an unclean spirit.”

*** Jesus' Mother and Brothers (Matthew 12:46--50; Luke 8:19--21)

<<3:31>> *31* Then Jesus' mother and brothers came and stood outside. They sent someone in to summon Him, 
<<3:32>> *32* and a crowd was sitting around Him. “Look,” He was told, “Your mother and brothers are outside, asking for You.”

<<3:33>> *33* But Jesus replied, “Who are My mother and My brothers?” 
<<3:34>> *34* Looking at those seated in a circle around Him, He said, “Here are My mother and My brothers! 
<<3:35>> *35* For whoever does the will of God is My brother and sister and mother.”

** Mark 4
*** The Parable of the Sower (Matthew 13:1--9; Luke 8:4--8)
[[html-class:drop][4]]

<<4:1>> Once again Jesus began to teach beside the sea, and such a large crowd gathered around Him that He got into a boat and sat in it, while all the people crowded along the shore.

<<4:2>> *2* And He taught them many things in parables, and in His teaching He said,
<<4:3>> *3* “Listen! A farmer went out to sow his seed. 
<<4:4>> *4* And as he was sowing, some seed fell along the path, and the birds came and devoured it.

<<4:5>> *5* Some fell on rocky ground, where it did not have much soil. It sprang up quickly because the soil was shallow. 
<<4:6>> *6* But when the sun rose, the seedlings were scorched, and they withered because they had no root.

<<4:7>> *7* Other seed fell among thorns, which grew up and choked the seedlings, and they yielded no crop.

<<4:8>> *8* Still other seed fell on good soil, where it sprouted, grew up, and produced a crop---one bearing thirtyfold, another sixtyfold, and another a hundredfold.”

<<4:9>> *9* Then Jesus said, “He who has ears to hear, let him hear.”

*** The Purpose of Jesus' Parables (Matthew 13:10--17; Luke 8:9--10)

<<4:10>> *10* As soon as Jesus was alone with the Twelve and those around Him, they asked Him about the parable.

<<4:11>> *11* He replied, “The mystery of the kingdom of God has been given to you, but to those on the outside everything is expressed in parables, 
<<4:12>> *12* so that,

‘they may be ever seeing but never perceiving,

and ever hearing but never understanding;

otherwise they might turn

and be forgiven.'”

*** The Parable of the Sower Explained (Matthew 13:18--23; Luke 8:11--15)

<<4:13>> *13* Then Jesus said to them, “Do you not understand this parable? Then how will you understand any of the parables?

<<4:14>> *14* The farmer sows the word. 
<<4:15>> *15* Some are like the seeds along the path, where the word is sown. As soon as they hear it, Satan comes and takes away the word that was sown in them.

<<4:16>> *16* Some are like the seeds sown on rocky ground. They hear the word and at once receive it with joy. 
<<4:17>> *17* But they themselves have no root, and they remain for only a season. When trouble or persecution comes because of the word, they quickly fall away.

<<4:18>> *18* Others are like the seeds sown among the thorns. They hear the word, 
<<4:19>> *19* but the worries of this life, the deceitfulness of wealth, and the desire for other things come in and choke the word, and it becomes unfruitful.

<<4:20>> *20* Still others are like the seeds sown on good soil. They hear the word, receive it, and produce a crop---thirtyfold, sixtyfold, or a hundredfold.”

*** The Lesson of the Lamp (Luke 8:16--18)

<<4:21>> *21* Jesus also said to them, “Does anyone bring in a lamp to put it under a basket or under a bed? Doesn't he set it on a stand? 
<<4:22>> *22* For there is nothing hidden that will not be disclosed, and nothing concealed that will not be brought to light.

<<4:23>> *23* If anyone has ears to hear, let him hear.”

<<4:24>> *24* He went on to say, “Pay attention to what you hear. With the measure you use, it will be measured to you, and even more will be added to you. 
<<4:25>> *25* For whoever has will be given more. But whoever does not have, even what he has will be taken away from him.”

*** The Seed Growing Secretly

<<4:26>> *26* Jesus also said, “The kingdom of God is like a man who scatters seed on the ground. 
<<4:27>> *27* Night and day he sleeps and wakes, and the seed sprouts and grows, though he knows not how. 
<<4:28>> *28* All by itself the earth produces a crop---first the stalk, then the head, then grain that ripens within. 
<<4:29>> *29* And as soon as the grain is ripe, he swings the sickle, because the harvest has come.”

*** The Parable of the Mustard Seed (Matthew 13:31--32; Luke 13:18--19)

<<4:30>> *30* Then He asked, “To what can we compare the kingdom of God? With what parable shall we present it? 
<<4:31>> *31* It is like a mustard seed, which is the smallest of all seeds sown upon the earth. 
<<4:32>> *32* But after it is planted, it grows to be the largest of all garden plants and puts forth great branches, so that the birds of the air nest in its shade.”

<<4:33>> *33* With many such parables Jesus spoke the word to them, to the extent that they could understand. 
<<4:34>> *34* He did not tell them anything without using a parable. But privately He explained everything to His own disciples.

*** Jesus Calms the Storm (Matthew 8:23--27; Luke 8:22--25)

<<4:35>> *35* When that evening came, He said to His disciples, “Let us cross to the other side.” 
<<4:36>> *36* After they had dismissed the crowd, they took Jesus with them, since He was already in the boat. And there were other boats with Him.

<<4:37>> *37* Soon a violent windstorm came up, and the waves were breaking over the boat, so that it was being swamped. 
<<4:38>> *38* But Jesus was in the stern, sleeping on the cushion. So they woke Him and said, “Teacher, don't You care that we are perishing?”

<<4:39>> *39* Then Jesus got up and rebuked the wind and the sea. “Silence!” He commanded. “Be still!” And the wind died down, and it was perfectly calm.

<<4:40>> *40* “Why are you so afraid?” He asked. “Do you still have no faith?”

<<4:41>> *41* Overwhelmed with fear, they asked one another, “Who is this, that even the wind and the sea obey Him?”

** Mark 5
*** The Demons and the Pigs (Matthew 8:28--34; Luke 8:26--39)
[[html-class:drop][5]]

<<5:1>> On the other side of the sea, they arrived in the region of the Gerasenes. 
<<5:2>> *2* As soon as Jesus got out of the boat, He was met by a man with an unclean spirit, who was coming from the tombs. 
<<5:3>> *3* This man had been living in the tombs and could no longer be restrained, even with chains. 
<<5:4>> *4* Though he was often bound with chains and shackles, he had broken the chains and shattered the shackles. Now there was no one with the strength to subdue him. 
<<5:5>> *5* Night and day in the tombs and in the mountains he kept crying out and cutting himself with stones.

<<5:6>> *6* When the man saw Jesus from a distance, he ran and fell on his knees before Him. 
<<5:7>> *7* And he shouted in a loud voice, “What do You want with me, Jesus, Son of the Most High God? I beg You before God not to torture me!” 
<<5:8>> *8* For Jesus had already declared, “Come out of this man, you unclean spirit!”

<<5:9>> *9* “What is your name?” Jesus asked.

“My name is Legion,” he replied, “for we are many.” 
<<5:10>> *10* And he begged Jesus repeatedly not to send them out of that region.

<<5:11>> *11* There on the nearby hillside a large herd of pigs was feeding. 
<<5:12>> *12* So the demons begged Jesus, “Send us to the pigs, so that we may enter them.”

<<5:13>> *13* He gave them permission, and the unclean spirits came out and went into the pigs, and the herd of about two thousand rushed down the steep bank into the sea and drowned in the water.

<<5:14>> *14* Those tending the pigs ran off and reported this in the town and countryside, and the people went out to see what had happened. 
<<5:15>> *15* When they came to Jesus, they saw the man who had been possessed by the legion of demons sitting there, clothed and in his right mind; and they were afraid.

<<5:16>> *16* Those who had seen it described what had happened to the demon-possessed man and also to the pigs. 
<<5:17>> *17* And the people began to beg Jesus to leave their region.

<<5:18>> *18* As He was getting into the boat, the man who had been possessed by the demons begged to go with Him. 
<<5:19>> *19* But Jesus would not allow him. “Go home to your own people,” He said, “and tell them how much the Lord has done for you, and what mercy He has shown you.”

<<5:20>> *20* So the man went away and began to proclaim throughout the Decapolis how much Jesus had done for him. And everyone was amazed.

*** The Healing Touch of Jesus (Matthew 9:18--26; Luke 8:40--56)

<<5:21>> *21* When Jesus had again crossed by boat to the other side, a large crowd gathered around Him beside the sea. 
<<5:22>> *22* A synagogue leader named Jairus arrived, and seeing Jesus, he fell at His feet 
<<5:23>> *23* and pleaded with Him urgently, “My little daughter is near death. Please come and place Your hands on her, so that she will be healed and live.”

<<5:24>> *24* So Jesus went with him, and a large crowd followed and pressed around Him. 
<<5:25>> *25* And a woman was there who had suffered from bleeding for twelve years. 
<<5:26>> *26* She had borne much agony under the care of many physicians and had spent all she had, but to no avail. Instead, her condition had only grown worse.

<<5:27>> *27* When the woman heard about Jesus, she came up through the crowd behind Him and touched His cloak. 
<<5:28>> *28* For she kept saying, “If only I touch His garments, I will be healed.” 
<<5:29>> *29* Immediately her bleeding stopped, and she sensed in her body that she was healed of her affliction.

<<5:30>> *30* At once Jesus was aware that power had gone out from Him. Turning to the crowd, He asked, “Who touched My garments?”

<<5:31>> *31* His disciples answered, “You can see the crowd pressing in on You, and yet You ask, ‘Who touched Me?'”

<<5:32>> *32* But He kept looking around to see who had done this. 
<<5:33>> *33* Then the woman, knowing what had happened to her, came and fell down before Him trembling in fear, and she told Him the whole truth.

<<5:34>> *34* “Daughter,” said Jesus, “your faith has healed you. Go in peace and be free of your affliction.”

<<5:35>> *35* While He was still speaking, messengers from the house of Jairus arrived and said, “Your daughter is dead; why bother the Teacher anymore?”

<<5:36>> *36* But Jesus overheard their conversation and said to Jairus, “Do not be afraid; just believe.” 
<<5:37>> *37* And He did not allow anyone to accompany Him except Peter, James, and John the brother of James.

<<5:38>> *38* When they arrived at the house of the synagogue leader, Jesus saw the commotion and the people weeping and wailing loudly. 
<<5:39>> *39* He went inside and asked, “Why all this commotion and weeping? The child is not dead, but asleep.” 
<<5:40>> *40* And they laughed at Him.

After He had put them all outside, He took the child's father and mother and His own companions, and went in to see the child. 
<<5:41>> *41* Taking her by the hand, Jesus said, “Talitha koum!” which means, “Little girl, I say to you, get up!” 
<<5:42>> *42* Immediately the girl got up and began to walk around. She was twelve years old, and at once they were utterly astounded. 
<<5:43>> *43* Then Jesus gave strict orders that no one should know about this, and He told them to give her something to eat.

** Mark 6
*** The Rejection at Nazareth (Matthew 13:53--58; Luke 4:16--30)
[[html-class:drop][6]]

<<6:1>> Jesus went on from there and came to His hometown, accompanied by His disciples. 
<<6:2>> *2* When the Sabbath came, He began to teach in the synagogue, and many who heard Him were astonished. “Where did this man get these ideas?” they asked. “What is this wisdom He has been given? And how can He perform such miracles? 
<<6:3>> *3* Isn't this the carpenter, the son of Mary and the brother of James, Joses, Judas, and Simon? Aren't His sisters here with us as well?” And they took offense at Him.

<<6:4>> *4* Then Jesus said to them, “Only in his hometown, among his relatives, and in his own household is a prophet without honor.” 
<<6:5>> *5* So He could not perform any miracles there, except to lay His hands on a few of the sick and heal them. 
<<6:6>> *6* And He was amazed at their unbelief.

*** And He went around from village to village, teaching the people.

*** The Ministry of the Twelve (Matthew 10:5--15; Luke 9:1--6)

<<6:7>> *7* Then Jesus called the Twelve to Him and began to send them out two by two, giving them authority over unclean spirits. 
<<6:8>> *8* He instructed them to take nothing but a staff for the journey---no bread, no bag, no money in their belts--- 
<<6:9>> *9* and to wear sandals, but not a second tunic.

<<6:10>> *10* And He told them, “When you enter a house, stay there until you leave that area. 
<<6:11>> *11* If anyone will not welcome you or listen to you, shake the dust off your feet when you leave that place, as a testimony against them.”

<<6:12>> *12* So they set out and preached that the people should repent. 
<<6:13>> *13* They also drove out many demons and healed many of the sick, anointing them with oil.

*** The Beheading of John (Matthew 14:1--12; Luke 9:7--9)

<<6:14>> *14* Now King Herod heard about this, for Jesus' name had become well known, and people were saying, “John the Baptist has risen from the dead! That is why miraculous powers are at work in him.” 
<<6:15>> *15* Others were saying, “He is Elijah,” and still others, “He is a prophet, like one of the prophets of old.”

<<6:16>> *16* But when Herod heard this, he said, “John, whom I beheaded, has risen from the dead!” 
<<6:17>> *17* For Herod himself had ordered that John be arrested and bound and imprisoned, on account of his brother Philip's wife Herodias, whom Herod had married. 
<<6:18>> *18* For John had been telling Herod, “It is not lawful for you to have your brother's wife!”

<<6:19>> *19* So Herodias held a grudge against John and wanted to kill him. But she had been unable, 
<<6:20>> *20* because Herod feared John and protected him, knowing that he was a righteous and holy man. When he heard John's words, he was greatly perplexed; yet he listened to him gladly.

<<6:21>> *21* On Herod's birthday, her opportunity arose. Herod held a banquet for his nobles and military commanders and the leading men of Galilee. 
<<6:22>> *22* When the daughter of Herodias came and danced, she pleased Herod and his guests, and the king said to the girl, “Ask me for whatever you wish, and I will give it to you.” 
<<6:23>> *23* And he swore to her, “Whatever you ask of me, I will give you, up to half my kingdom!”

<<6:24>> *24* Then she went out and asked her mother, “What should I request?”

*** And her mother answered, “The head of John the Baptist.”

<<6:25>> *25* At once the girl hurried back to the king with her request: “I want you to give me the head of John the Baptist on a platter immediately.”

<<6:26>> *26* The king was consumed with sorrow, but because of his oaths and his guests, he did not want to refuse her. 
<<6:27>> *27* So without delay, the king commanded that John's head be brought in. He sent an executioner, who went and beheaded him in the prison. 
<<6:28>> *28* The man brought John's head on a platter and presented it to the girl, who gave it to her mother.

<<6:29>> *29* When John's disciples heard about this, they came and took his body and placed it in a tomb.

*** The Feeding of the Five Thousand (Luke 9:10--17; John 6:1--15)

<<6:30>> *30* Meanwhile, the apostles gathered around Jesus and brought Him news of all they had done and taught. 
<<6:31>> *31* And He said to them, “Come with Me privately to a solitary place, and let us rest for a while.” For many people were coming and going, and they did not even have time to eat.

<<6:32>> *32* So they went away in a boat by themselves to a solitary place. 
<<6:33>> *33* But many people saw them leaving and recognized them. They ran together on foot from all the towns and arrived before them. 
<<6:34>> *34* When Jesus stepped ashore and saw a large crowd, He had compassion on them, because they were like sheep without a shepherd. And He began to teach them many things.

<<6:35>> *35* By now the hour was already late. So the disciples came to Jesus and said, “This is a desolate place, and the hour is already late. 
<<6:36>> *36* Dismiss the crowd so they can go to the surrounding countryside and villages and buy themselves something to eat.”

<<6:37>> *37* But Jesus told them, “You give them something to eat.”

They asked Him, “Should we go out and spend two hundred denarii to give all of them bread to eat?”

<<6:38>> *38* “Go and see how many loaves you have,” He told them.

And after checking, they said, “Five---and two fish.”

<<6:39>> *39* Then Jesus directed them to have the people sit in groups on the green grass. 
<<6:40>> *40* So they sat down in groups of hundreds and fifties.

<<6:41>> *41* Taking the five loaves and the two fish and looking up to heaven, Jesus spoke a blessing and broke the loaves. Then He gave them to His disciples to set before the people. And He divided the two fish among them all.

<<6:42>> *42* They all ate and were satisfied, 
<<6:43>> *43* and the disciples picked up twelve basketfuls of broken pieces of bread and fish. 
<<6:44>> *44* And there were five thousand men who had eaten the loaves.

*** Jesus Walks on Water (Matthew 14:22--33; John 6:16--21)

<<6:45>> *45* Immediately Jesus made His disciples get into the boat and go on ahead of Him to Bethsaida, while He dismissed the crowd. 
<<6:46>> *46* After bidding them farewell, He went up on the mountain to pray.

<<6:47>> *47* When evening came, the boat was in the middle of the sea, and Jesus was alone on land. 
<<6:48>> *48* He could see that the disciples were straining to row, because the wind was against them. About the fourth watch of the night, Jesus went out to them, walking on the sea. He intended to pass by them, 
<<6:49>> *49* but when they saw Him walking on the sea, they cried out, thinking He was a ghost--- 
<<6:50>> *50* for they all saw Him and were terrified.

But Jesus spoke up at once: “Take courage! It is I. Do not be afraid.” 
<<6:51>> *51* Then He climbed into the boat with them, and the wind died down. And the disciples were utterly astounded, 
<<6:52>> *52* for they had not understood about the loaves, but their hearts had been hardened.

*** Jesus Heals at Gennesaret (Matthew 14:34--36)

<<6:53>> *53* When they had crossed over, they landed at Gennesaret and moored the boat. 
<<6:54>> *54* As soon as they got out of the boat, the people recognized Jesus 
<<6:55>> *55* and ran through that whole region, carrying the sick on mats to wherever they heard He was. 
<<6:56>> *56* And wherever He went---villages and towns and countrysides---they laid the sick in the marketplaces and begged Him just to let them touch the fringe of His cloak. And all who touched Him were healed.

** Mark 7
*** The Tradition of the Elders (Matthew 15:1--9)
[[html-class:drop][7]]

<<7:1>> Then the Pharisees and some of the scribes who had come from Jerusalem gathered around Jesus, 
<<7:2>> *2* and they saw some of His disciples eating with hands that were defiled---that is, unwashed.

<<7:3>> *3* Now in holding to the tradition of the elders, the Pharisees and all the Jews do not eat until they wash their hands ceremonially. 
<<7:4>> *4* And on returning from the market, they do not eat unless they wash. And there are many other traditions for them to observe, including the washing of cups, pitchers, kettles, and couches for dining.

<<7:5>> *5* So the Pharisees and scribes questioned Jesus: “Why do Your disciples not walk according to the tradition of the elders? Instead, they eat with defiled hands.”

<<7:6>> *6* Jesus answered them, “Isaiah prophesied correctly about you hypocrites, as it is written:

‘These people honor Me with their lips,

but their hearts are far from Me.

<<7:7>> *7* They worship Me in vain;

they teach as doctrine the precepts of men.'

<<7:8>> *8* You have disregarded the commandment of God to keep the tradition of men.”

<<7:9>> *9* He went on to say, “You neatly set aside the command of God to maintain your own tradition. 
<<7:10>> *10* For Moses said, ‘Honor your father and your mother' and ‘Anyone who curses his father or mother must be put to death.' 
<<7:11>> *11* But you say that if a man says to his father or mother, ‘Whatever you would have received from me is Corban' (that is, a gift devoted to God), 
<<7:12>> *12* he is no longer permitted to do anything for his father or mother. 
<<7:13>> *13* Thus you nullify the word of God by the tradition you have handed down. And you do so in many such matters.”

*** What Defiles a Man (Matthew 15:10--20)

<<7:14>> *14* Once again Jesus called the crowd to Him and said, “All of you, listen to Me and understand: 
<<7:15>> *15* Nothing that enters a man from the outside can defile him; but the things that come out of a man, these are what defile him.”

<<7:17>> *17* After Jesus had left the crowd and gone into the house, His disciples inquired about the parable.

<<7:18>> *18* “Are you still so dull?” He asked. “Do you not understand? Nothing that enters a man from the outside can defile him, 
<<7:19>> *19* because it does not enter his heart, but it goes into the stomach and then is eliminated.” (Thus all foods are clean.)

<<7:20>> *20* He continued: “What comes out of a man, that is what defiles him. 
<<7:21>> *21* For from within the hearts of men come evil thoughts, sexual immorality, theft, murder, adultery, 
<<7:22>> *22* greed, wickedness, deceit, debauchery, envy, slander, arrogance, and foolishness. 
<<7:23>> *23* All these evils come from within, and these are what defile a man.”

*** The Faith of the Gentile Woman (Matthew 15:21--28)

<<7:24>> *24* Jesus left that place and went to the region of Tyre. Not wanting anyone to know He was there, He entered a house, but was unable to escape their notice. 
<<7:25>> *25* Instead, a woman whose little daughter had an unclean spirit soon heard about Jesus, and she came and fell at His feet. 
<<7:26>> *26* Now she was a Greek woman of Syrophoenician origin, and she kept asking Jesus to drive the demon out of her daughter.

<<7:27>> *27* “First let the children have their fill,” He said. “For it is not right to take the children's bread and toss it to the dogs.”

<<7:28>> *28* “Yes, Lord,” she replied, “even the dogs under the table eat the children's crumbs.”

<<7:29>> *29* Then Jesus told her, “Because of this answer, you may go. The demon has left your daughter.” 
<<7:30>> *30* And she went home and found her child lying on the bed, and the demon was gone.

*** The Deaf and Mute Man (Matthew 9:27--34)

<<7:31>> *31* Then Jesus left the region of Tyre and went through Sidon to the Sea of Galilee and into the region of the Decapolis. 
<<7:32>> *32* Some people brought to Him a man who was deaf and hardly able to speak, and they begged Jesus to place His hand on him.

<<7:33>> *33* So Jesus took him aside privately, away from the crowd, and put His fingers into the man's ears. Then He spit and touched the man's tongue. 
<<7:34>> *34* And looking up to heaven, He sighed deeply and said to him, “Ephphatha!” (which means, “Be opened!”). 
<<7:35>> *35* Immediately the man's ears were opened and his tongue was released, and he began to speak plainly.

<<7:36>> *36* Jesus ordered them not to tell anyone. But the more He ordered them, the more widely they proclaimed it. 
<<7:37>> *37* The people were utterly astonished and said, “He has done all things well! He makes even the deaf hear and the mute speak!”

** Mark 8
*** The Feeding of the Four Thousand (2 Kings 4:42--44; Matthew 15:29--39)
[[html-class:drop][8]]

<<8:1>> In those days the crowd once again became very large, and they had nothing to eat. Jesus called the disciples to Him and said,
<<8:2>> *2* “I have compassion for this crowd, because they have already been with Me three days and have nothing to eat. 
<<8:3>> *3* If I send them home hungry, they will faint along the way. For some of them have come a great distance.”

<<8:4>> *4* His disciples replied, “Where in this desolate place could anyone find enough bread to feed all these people?”

<<8:5>> *5* “How many loaves do you have?” Jesus asked.

“Seven,” they replied.

<<8:6>> *6* And He instructed the crowd to sit down on the ground. Then He took the seven loaves, gave thanks and broke them, and gave them to His disciples to set before the people. And they distributed them to the crowd. 
<<8:7>> *7* They also had a few small fish, and Jesus blessed them and ordered that these be set before them as well.

<<8:8>> *8* The people ate and were satisfied, and the disciples picked up seven basketfuls of broken pieces that were left over. 
<<8:9>> *9* And about four thousand men were present.

As soon as Jesus had dismissed the crowd, 
<<8:10>> *10* He got into the boat with His disciples and went to the district of Dalmanutha.

*** The Demand for a Sign (Matthew 16:1--4; Luke 12:54--56)

<<8:11>> *11* Then the Pharisees came and began to argue with Jesus, testing Him by demanding from Him a sign from heaven.

<<8:12>> *12* Jesus sighed deeply in His spirit and said, “Why does this generation demand a sign? Truly I tell you, no sign will be given to this generation.” 
<<8:13>> *13* And He left them, got back into the boat, and crossed to the other side.

*** The Leaven of the Pharisees and of Herod (Matthew 16:5--12; Luke 12:1--3)

<<8:14>> *14* Now the disciples had forgotten to take bread, except for one loaf they had with them in the boat.
<<8:15>> *15* “Watch out!” He cautioned them. “Beware of the leaven of the Pharisees and of Herod.”

<<8:16>> *16* So they began to discuss with one another the fact that they had no bread.

<<8:17>> *17* Aware of their conversation, Jesus asked them, “Why are you debating about having no bread? Do you still not see or understand? Do you have such hard hearts? 18‘Having eyes, do you not see? And having ears, do you not hear?' And do you not remember? 
<<8:19>> *19* When I broke the five loaves for the five thousand, how many basketfuls of broken pieces did you collect?”

“Twelve,” they answered.

<<8:20>> *20* “And when I broke the seven loaves for the four thousand, how many basketfuls of broken pieces did you collect?”

“Seven,” they said.

<<8:21>> *21* Then He asked them, “Do you still not understand?”

*** The Blind Man at Bethsaida

<<8:22>> *22* When they arrived at Bethsaida, some people brought a blind man and begged Jesus to touch him. 
<<8:23>> *23* So He took the blind man by the hand and led him out of the village. Then He spit on the man's eyes and placed His hands on him. “Can you see anything?” He asked.

<<8:24>> *24* The man looked up and said, “I can see the people, but they look like trees walking around.”

<<8:25>> *25* Once again Jesus placed His hands on the man's eyes, and when he opened them his sight was restored, and he could see everything clearly. 
<<8:26>> *26* Jesus sent him home and said, “Do not go back into the village.”

*** Peter's Confession of Christ (Luke 9:18--20; John 6:67--71)

<<8:27>> *27* Then Jesus and His disciples went on to the villages around Caesarea Philippi. On the way, He questioned His disciples: “Who do people say I am?”

<<8:28>> *28* They replied, “Some say John the Baptist; others say Elijah; and still others, one of the prophets.”

<<8:29>> *29* “But what about you?” Jesus asked. “Who do you say I am?”

*** Peter answered, “You are the Christ.”

<<8:30>> *30* And Jesus warned them not to tell anyone about Him.

*** Christ's Passion Foretold (Matthew 16:21--23; Luke 9:21--22)

<<8:31>> *31* Then He began to teach them that the Son of Man must suffer many things and be rejected by the elders, chief priests, and scribes, and that He must be killed and after three days rise again. 
<<8:32>> *32* He spoke this message quite frankly, and Peter took Him aside and began to rebuke Him.

<<8:33>> *33* But Jesus, turning and looking at His disciples, rebuked Peter and said, “Get behind Me, Satan! For you do not have in mind the things of God, but the things of men.”

*** Take Up Your Cross (Matthew 16:24--28; Luke 9:23--27)

<<8:34>> *34* Then Jesus called the crowd to Him along with His disciples, and He told them, “If anyone wants to come after Me, he must deny himself and take up his cross and follow Me. 
<<8:35>> *35* For whoever wants to save his life will lose it, but whoever loses his life for My sake and for the gospel will save it.

<<8:36>> *36* What does it profit a man to gain the whole world, yet forfeit his soul? 
<<8:37>> *37* Or what can a man give in exchange for his soul? 
<<8:38>> *38* If anyone is ashamed of Me and My words in this adulterous and sinful generation, the Son of Man will also be ashamed of him when He comes in His Father's glory with the holy angels.”

** Mark 9
*** The Transfiguration (Luke 9:28--36; 2 Peter 1:16--21)
[[html-class:drop][9]]

<<9:1>> Then Jesus said to them, “Truly I tell you, there are some standing here who will not taste death before they see the kingdom of God arrive with power.”

<<9:2>> *2* After six days Jesus took with Him Peter, James, and John, and led them up a high mountain by themselves. There He was transfigured before them. 
<<9:3>> *3* His clothes became radiantly white, brighter than any launderer on earth could bleach them. 
<<9:4>> *4* And Elijah and Moses appeared before them, talking with Jesus.

<<9:5>> *5* Peter said to Jesus, “Rabbi, it is good for us to be here. Let us put up three shelters---one for You, one for Moses, and one for Elijah.” 
<<9:6>> *6* For they were all so terrified that Peter did not know what else to say.

<<9:7>> *7* Then a cloud appeared and enveloped them, and a voice came from the cloud: “This is My beloved Son. Listen to Him!” 
<<9:8>> *8* Suddenly, when they looked around, they saw no one with them except Jesus.

<<9:9>> *9* As they were coming down the mountain, Jesus admonished them not to tell anyone what they had seen until the Son of Man had risen from the dead. 
<<9:10>> *10* So they kept this matter to themselves, discussing what it meant to rise from the dead. 
<<9:11>> *11* And they asked Jesus, “Why do the scribes say that Elijah must come first?”

<<9:12>> *12* He replied, “Elijah does indeed come first, and he restores all things. Why then is it written that the Son of Man must suffer many things and be rejected? 
<<9:13>> *13* But I tell you that Elijah has indeed come, and they have done to him whatever they wished, just as it is written about him.”

*** The Boy with an Evil Spirit (Matthew 17:14--18; Luke 9:37--42)

<<9:14>> *14* When they returned to the other disciples, they saw a large crowd around them, and scribes arguing with them. 
<<9:15>> *15* As soon as all the people saw Jesus, they were filled with awe and ran to greet Him.

<<9:16>> *16* “What are you disputing with them?” He asked.

<<9:17>> *17* Someone in the crowd replied, “Teacher, I brought You my son, who has a spirit that makes him mute. 
<<9:18>> *18* Whenever it seizes him, it throws him to the ground. He foams at the mouth, gnashes his teeth, and becomes rigid. I asked Your disciples to drive it out, but they were unable.”

<<9:19>> *19* “O unbelieving generation!” Jesus replied. “How long must I remain with you? How long must I put up with you? Bring the boy to Me.”

<<9:20>> *20* So they brought him, and seeing Jesus, the spirit immediately threw the boy into a convulsion. He fell to the ground and rolled around, foaming at the mouth.

<<9:21>> *21* Jesus asked the boy's father, “How long has this been with him?”

“From childhood,” he said.
<<9:22>> *22* “It often throws him into the fire or into the water, trying to kill him. But if You can do anything, have compassion on us and help us.”

<<9:23>> *23* “If You can?” echoed Jesus. “All things are possible to him who believes!”

<<9:24>> *24* Immediately the boy's father cried out, “I do believe; help my unbelief!”

<<9:25>> *25* When Jesus saw that a crowd had come running, He rebuked the unclean spirit. “You deaf and mute spirit,” He said, “I command you to come out and never enter him again.”

<<9:26>> *26* After shrieking and convulsing him violently, the spirit came out. The boy became like a corpse, so that many said, “He is dead.” 
<<9:27>> *27* But Jesus took him by the hand and helped him to his feet, and he stood up.

<<9:28>> *28* After Jesus had gone into the house, His disciples asked Him privately, “Why couldn't we drive it out?”

<<9:29>> *29* Jesus answered, “This kind cannot come out, except by prayer.”

*** The Second Prediction of the Passion (Matthew 17:22--23; Luke 9:43--45)

<<9:30>> *30* Going on from there, they passed through Galilee. But Jesus did not want anyone to know, 
<<9:31>> *31* because He was teaching His disciples. He told them, “The Son of Man will be delivered into the hands of men. They will kill Him, and after three days He will rise.” 
<<9:32>> *32* But they did not understand this statement, and they were afraid to ask Him about it.

*** The Greatest in the Kingdom (Matthew 18:1--5; Luke 9:46--50)

<<9:33>> *33* Then they came to Capernaum. While Jesus was in the house, He asked them, “What were you discussing on the way?” 
<<9:34>> *34* But they were silent, for on the way they had been arguing about which of them was the greatest.

<<9:35>> *35* Sitting down, Jesus called the Twelve and said, “If anyone wants to be first, he must be the last of all and the servant of all.”

<<9:36>> *36* Then He had a little child stand among them. Taking the child in His arms, He said to them,
<<9:37>> *37* “Whoever welcomes one of these little children in My name welcomes Me, and whoever welcomes Me welcomes not only Me, but the One who sent Me.”

<<9:38>> *38* John said to Him, “Teacher, we saw someone else driving out demons in Your name, and we tried to stop him, because he does not accompany us.”

<<9:39>> *39* “Do not stop him,” Jesus replied. “For no one who performs a miracle in My name can turn around and speak evil of Me. 
<<9:40>> *40* For whoever is not against us is for us. 
<<9:41>> *41* Indeed, if anyone gives you even a cup of water because you bear the name of Christ, truly I tell you, he will never lose his reward.

*** Temptations and Trespasses (Matthew 18:6--9; Luke 17:1--4)

<<9:42>> *42* But if anyone causes one of these little ones who believe in Me to stumble, it would be better for him to have a large millstone hung around his neck and to be thrown into the sea.

<<9:43>> *43* If your hand causes you to sin, cut it off. It is better for you to enter life crippled than to have two hands and go into hell, into the unquenchable fire. 
<<9:45>> *45* If your foot causes you to sin, cut it off. It is better for you to enter life lame than to have two feet and be thrown into hell. 
<<9:47>> *47* And if your eye causes you to sin, pluck it out. It is better for you to enter the kingdom of God with one eye than to have two eyes and be thrown into hell, 
<<9:48>> *48* where ‘their worm never dies, and the fire is never quenched.'

*** Good Salt (Matthew 5:13--16; Luke 14:34--35)

<<9:49>> *49* For everyone will be salted with fire.

<<9:50>> *50* Salt is good, but if the salt loses its saltiness, with what will you season it? Have salt among yourselves, and be at peace with one another.”

** Mark 10
*** Teachings about Divorce (Matthew 19:1--12)
[[html-class:drop][10]]

<<10:1>> Then Jesus left that place and went into the region of Judea, beyond the Jordan. Again the crowds came to Him and He taught them, as was His custom.

<<10:2>> *2* Some Pharisees came to test Him. “Is it lawful for a man to divorce his wife?” they inquired.

<<10:3>> *3* “What did Moses command you?” He replied.

<<10:4>> *4* They answered, “Moses permitted a man to write his wife a certificate of divorce and send her away.”

<<10:5>> *5* But Jesus told them, “Moses wrote this commandment for you because of your hardness of heart. 
<<10:6>> *6* However, from the beginning of creation, ‘God made them male and female.' 7‘For this reason a man will leave his father and mother and be united to his wife, 
<<10:8>> *8* and the two will become one flesh.' So they are no longer two, but one flesh. 
<<10:9>> *9* Therefore what God has joined together, let man not separate.”

<<10:10>> *10* When they were back inside the house, the disciples asked Jesus about this matter. 
<<10:11>> *11* So He told them, “Whoever divorces his wife and marries another woman commits adultery against her. 
<<10:12>> *12* And if a woman divorces her husband and marries another man, she commits adultery.”

*** Jesus Blesses the Children (Matthew 19:13--15; Luke 18:15--17)

<<10:13>> *13* Now people were bringing the little children to Jesus for Him to place His hands on them, and the disciples rebuked those who brought them.

<<10:14>> *14* But when Jesus saw this, He was indignant and told them, “Let the little children come to Me, and do not hinder them! For the kingdom of God belongs to such as these. 
<<10:15>> *15* Truly I tell you, anyone who does not receive the kingdom of God like a little child will never enter it.” 
<<10:16>> *16* And He took the children in His arms, placed His hands on them, and blessed them.

*** The Rich Young Man (Matthew 19:16--30; Luke 18:18--30)

<<10:17>> *17* As Jesus started on His way, a man ran up and knelt before Him. “Good Teacher,” he asked, “what must I do to inherit eternal life?”

<<10:18>> *18* “Why do you call Me good?” Jesus replied. “No one is good except God alone. 
<<10:19>> *19* You know the commandments: ‘Do not murder, do not commit adultery, do not steal, do not bear false witness, do not cheat others, honor your father and mother.'”

<<10:20>> *20* “Teacher,” he replied, “all these I have kept from my youth.”

<<10:21>> *21* Jesus looked at him, loved him, and said to him, “There is one thing you lack: Go, sell everything you own and give to the poor, and you will have treasure in heaven. Then come, follow Me.”

<<10:22>> *22* But the man was saddened by these words and went away in sorrow, because he had great wealth.

<<10:23>> *23* Then Jesus looked around and said to His disciples, “How hard it is for the rich to enter the kingdom of God!”

<<10:24>> *24* And the disciples were amazed at His words.

But Jesus said to them again, “Children, how hard it is to enter the kingdom of God! 
<<10:25>> *25* It is easier for a camel to pass through the eye of a needle than for a rich man to enter the kingdom of God.”

<<10:26>> *26* They were even more astonished and said to one another, “Who then can be saved?”

<<10:27>> *27* Jesus looked at them and said, “With man this is impossible, but not with God. For all things are possible with God.”

<<10:28>> *28* Peter began to say to Him, “Look, we have left everything and followed You.”

<<10:29>> *29* “Truly I tell you,” Jesus replied, “no one who has left home or brothers or sisters or mother or father or children or fields for My sake and for the gospel 
<<10:30>> *30* will fail to receive a hundredfold in the present age---houses and brothers and sisters and mothers and children and fields, along with persecutions---and in the age to come, eternal life. 
<<10:31>> *31* But many who are first will be last, and the last will be first.”

*** The Third Prediction of the Passion (Matthew 20:17--19; Luke 18:31--34)

<<10:32>> *32* As they were going up the road to Jerusalem, Jesus was walking ahead of them. The disciples were amazed, but those who followed were afraid. Again Jesus took the Twelve aside and began to tell them what was going to happen to Him:
<<10:33>> *33* “Look, we are going up to Jerusalem, and the Son of Man will be delivered over to the chief priests and scribes. They will condemn Him to death and will deliver Him over to the Gentiles, 
<<10:34>> *34* who will mock Him and spit on Him and flog Him and kill Him. And after three days He will rise again.”

*** The Request of James and John (Matthew 20:20--28)

<<10:35>> *35* Then James and John, the sons of Zebedee, came to Jesus and declared, “Teacher, we want You to do for us whatever we ask.”

<<10:36>> *36* “What do you want Me to do for you?” He inquired.

<<10:37>> *37* They answered, “Grant that one of us may sit at Your right hand and the other at Your left in Your glory.”

<<10:38>> *38* “You do not know what you are asking,” Jesus replied. “Can you drink the cup I will drink, or be baptized with the baptism I will undergo?”

<<10:39>> *39* “We can,” the brothers answered.

“You will drink the cup that I drink,” Jesus said, “and you will be baptized with the baptism that I undergo. 
<<10:40>> *40* But to sit at My right or left is not Mine to grant. These seats belong to those for whom they have been prepared.”

<<10:41>> *41* When the ten heard about this, they became indignant with James and John. 
<<10:42>> *42* So Jesus called them together and said, “You know that those regarded as rulers of the Gentiles lord it over them, and their superiors exercise authority over them. 
<<10:43>> *43* But it shall not be this way among you. Instead, whoever wants to become great among you must be your servant, 
<<10:44>> *44* and whoever wants to be first must be the slave of all. 
<<10:45>> *45* For even the Son of Man did not come to be served, but to serve, and to give His life as a ransom for many.”

*** Jesus Heals Bartimaeus (Matthew 20:29--34; Luke 18:35--43)

<<10:46>> *46* Next, they came to Jericho. And as Jesus and His disciples were leaving Jericho with a large crowd, a blind beggar named Bartimaeus, the son of Timaeus, was sitting beside the road. 
<<10:47>> *47* When he heard that it was Jesus of Nazareth, he began to cry out, “Jesus, Son of David, have mercy on me!”

<<10:48>> *48* Many people admonished him to be silent, but he cried out all the louder, “Son of David, have mercy on me!”

<<10:49>> *49* Jesus stopped and said, “Call him.”

So they called the blind man. “Take courage!” they said. “Get up! He is calling for you.”

<<10:50>> *50* Throwing off his cloak, Bartimaeus jumped up and came to Jesus.

<<10:51>> *51* “What do you want Me to do for you?” Jesus asked.

“Rabboni,” said the blind man, “let me see again.”

<<10:52>> *52* “Go,” said Jesus, “your faith has healed you.” And immediately he received his sight and followed Jesus along the road.

** Mark 11
*** The Triumphal Entry (Luke 19:28--40; John 12:12--19)
[[html-class:drop][11]]

<<11:1>> As they approached Jerusalem and came to Bethphage and Bethany at the Mount of Olives, Jesus sent out two of His disciples 
<<11:2>> *2* and said to them, “Go into the village ahead of you, and as soon as you enter it, you will find a colt tied there, on which no one has ever sat. Untie it and bring it here. 
<<11:3>> *3* If anyone asks, ‘Why are you doing this?' tell him, ‘The Lord needs it and will return it shortly.' ”

<<11:4>> *4* So they went and found the colt outside in the street, tied at a doorway. They untied it, 
<<11:5>> *5* and some who were standing there asked, “Why are you untying the colt?”

<<11:6>> *6* The disciples answered as Jesus had instructed them, and the people gave them permission. 
<<11:7>> *7* Then they led the colt to Jesus and threw their cloaks over it, and He sat on it.

<<11:8>> *8* Many in the crowd spread their cloaks on the road, while others spread branches they had cut from the fields. 
<<11:9>> *9* The ones who went ahead and those who followed were shouting:

“Hosanna!”

“Blessed is He who comes in the name of the Lord!”

<<11:10>> *10* “Blessed is the coming kingdom of our father David!”

“Hosanna in the highest!”

<<11:11>> *11* Then Jesus entered Jerusalem and went into the temple courts. He looked around at everything, but since it was already late, He went out to Bethany with the Twelve.

*** Jesus Curses the Fig Tree (Matthew 21:18--22; Mark 11:20--25)

<<11:12>> *12* The next day, when they had left Bethany, Jesus was hungry. 
<<11:13>> *13* Seeing in the distance a fig tree in leaf, He went to see if there was any fruit on it. But when He reached it, He found nothing on it except leaves, since it was not the season for figs. 
<<11:14>> *14* Then He said to the tree, “May no one ever eat of your fruit again.” And His disciples heard this statement.

*** Jesus Cleanses the Temple (Luke 19:45--48; John 2:12--25)

<<11:15>> *15* When they arrived in Jerusalem, Jesus entered the temple courts and began to drive out those who were buying and selling there. He overturned the tables of the money changers and the seats of those selling doves. 
<<11:16>> *16* And He would not allow anyone to carry merchandise through the temple courts. 
<<11:17>> *17* Then Jesus began to teach them, and He declared, “Is it not written: ‘My house will be called a house of prayer for all the nations'? But you have made it ‘a den of robbers.'”

<<11:18>> *18* When the chief priests and scribes heard this, they looked for a way to kill Him. For they were afraid of Him, because the whole crowd was astonished at His teaching.

<<11:19>> *19* And when evening came, Jesus and His disciples went out of the city.

*** The Withered Fig Tree (Matthew 21:18--22; Mark 11:12--14)

<<11:20>> *20* As they were walking back in the morning, they saw the fig tree withered from its roots. 
<<11:21>> *21* Peter remembered it and said, “Look, Rabbi! The fig tree You cursed has withered.”

<<11:22>> *22* “Have faith in God,” Jesus said to them.
<<11:23>> *23* “Truly I tell you that if anyone says to this mountain, ‘Be lifted up and thrown into the sea,' and has no doubt in his heart but believes that it will happen, it will be done for him. 
<<11:24>> *24* Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.

<<11:25>> *25* And when you stand to pray, if you hold anything against another, forgive it, so that your Father in heaven will forgive your trespasses as well.”

*** Jesus' Authority Challenged (Matthew 21:23--27; Luke 20:1--8)

<<11:27>> *27* After their return to Jerusalem, Jesus was walking in the temple courts, and the chief priests, scribes, and elders came up to Him.
<<11:28>> *28* “By what authority are You doing these things?” they asked. “And who gave You the authority to do them?”

<<11:29>> *29* “I will ask you one question,” Jesus replied, “and if you answer Me, I will tell you by what authority I am doing these things. 
<<11:30>> *30* John's baptism---was it from heaven or from men? Answer Me!”

<<11:31>> *31* They deliberated among themselves what they should answer: “If we say, ‘From heaven,' He will ask, ‘Why then did you not believe him?' 
<<11:32>> *32* But if we say, ‘From men'...” they were afraid of the people, for they all held that John truly was a prophet. 
<<11:33>> *33* So they answered, “We do not know.”

And Jesus replied, “Neither will I tell you by what authority I am doing these things.”

** Mark 12
*** The Parable of the Wicked Tenants (Matthew 21:33--46; Luke 20:9--18)
[[html-class:drop][12]]

<<12:1>> Then Jesus began to speak to them in parables: “A man planted a vineyard. He put a wall around it, dug a wine vat, and built a watchtower. Then he rented it out to some tenants and went away on a journey.

<<12:2>> *2* At harvest time, he sent a servant to the tenants to collect his share of the fruit of the vineyard. 
<<12:3>> *3* But they seized the servant, beat him, and sent him away empty-handed.

<<12:4>> *4* Then he sent them another servant, and they struck him over the head and treated him shamefully.

<<12:5>> *5* He sent still another, and this one they killed.

He sent many others; some they beat and others they killed.

<<12:6>> *6* Finally, having one beloved son, he sent him to them. ‘They will respect my son,' he said.

<<12:7>> *7* But the tenants said to one another, ‘This is the heir. Come, let us kill him, and the inheritance will be ours.' 
<<12:8>> *8* So they seized the son, killed him, and threw him out of the vineyard.

<<12:9>> *9* What then will the owner of the vineyard do? He will come and kill those tenants, and will give the vineyard to others. 
<<12:10>> *10* Have you never read this Scripture:

‘The stone the builders rejected

has become the cornerstone.

<<12:11>> *11* This is from the Lord,

and it is marvelous in our eyes'?”

<<12:12>> *12* At this, the leaders sought to arrest Jesus, for they knew that He had spoken this parable against them. But fearing the crowd, they left Him and went away.

*** Paying Taxes to Caesar (Matthew 22:15--22; Luke 20:19--26)

<<12:13>> *13* Later, they sent some of the Pharisees and Herodians to catch Jesus in His words.
<<12:14>> *14* “Teacher,” they said, “we know that You are honest and seek favor from no one. Indeed, You are impartial and teach the way of God in accordance with the truth. Is it lawful to pay taxes to Caesar or not? Should we pay them or not?”

<<12:15>> *15* But Jesus saw through their hypocrisy and said, “Why are you testing Me? Bring Me a denarius to inspect.” 
<<12:16>> *16* So they brought it, and He asked them, “Whose image is this? And whose inscription?”

“Caesar's,” they answered.

<<12:17>> *17* Then Jesus told them, “Give to Caesar what is Caesar's, and to God what is God's.”

And they marveled at Him.

*** The Sadducees and the Resurrection (Matthew 22:23--33; Luke 20:27--40)

<<12:18>> *18* Then the Sadducees, who say there is no resurrection, came to Jesus and questioned Him:
<<12:19>> *19* “Teacher, Moses wrote for us that if a man's brother dies and leaves a wife but no children, the man is to marry his brother's widow and raise up offspring for him. 
<<12:20>> *20* Now there were seven brothers. The first one married and died, leaving no children. 
<<12:21>> *21* Then the second one married the widow, but he also died and left no children. And the third did likewise. 
<<12:22>> *22* In this way, none of the seven left any children. And last of all, the woman died. 
<<12:23>> *23* In the resurrection, then, whose wife will she be? For all seven were married to her.”

<<12:24>> *24* Jesus said to them, “Aren't you mistaken, because you do not know the Scriptures or the power of God? 
<<12:25>> *25* When the dead rise, they will neither marry nor be given in marriage. Instead, they will be like the angels in heaven.

<<12:26>> *26* But concerning the dead rising, have you not read about the burning bush in the Book of Moses, how God told him, ‘I am the God of Abraham, the God of Isaac, and the God of Jacob'? 
<<12:27>> *27* He is not the God of the dead, but of the living. You are badly mistaken!”

*** The Greatest Commandment (Deuteronomy 6:1--19; Matthew 22:34--40)

<<12:28>> *28* Now one of the scribes had come up and heard their debate. Noticing how well Jesus had answered them, he asked Him, “Which commandment is the most important of all?”

<<12:29>> *29* Jesus replied, “This is the most important: ‘Hear O Israel, the Lord our God, the Lord is One. 
<<12:30>> *30* Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength.' 
<<12:31>> *31* The second is this: ‘Love your neighbor as yourself.' No other commandment is greater than these.”

<<12:32>> *32* “Right, Teacher,” the scribe replied. “You have stated correctly that God is One and there is no other but Him, 
<<12:33>> *33* and to love Him with all your heart and with all your understanding and with all your strength, and to love your neighbor as yourself, which is more important than all burnt offerings and sacrifices.”

<<12:34>> *34* When Jesus saw that the man had answered wisely, He said, “You are not far from the kingdom of God.”

And no one dared to question Him any further.

*** Whose Son Is the Christ? (Matthew 22:41--46; Luke 20:41--44)

<<12:35>> *35* While Jesus was teaching in the temple courts, He asked, “How can the scribes say that the Christ is the Son of David? 
<<12:36>> *36* Speaking by the Holy Spirit, David himself declared:

‘The Lord said to my Lord,

“Sit at My right hand

until I put Your enemies

under Your feet.” '

<<12:37>> *37* David himself calls Him ‘Lord.' So how can He be David's son?”

And the large crowd listened to Him with delight.

*** Beware of the Scribes (Luke 20:45--47)

<<12:38>> *38* In His teaching Jesus also said, “Watch out for the scribes. They like to walk around in long robes, to receive greetings in the marketplaces, 
<<12:39>> *39* and to have the chief seats in the synagogues and the places of honor at banquets. 
<<12:40>> *40* They defraud widows of their houses, and for a show make lengthy prayers. These men will receive greater condemnation.”

*** The Widow's Offering (Luke 21:1--4)

<<12:41>> *41* As Jesus was sitting opposite the treasury, He watched the crowd putting money into it. And many rich people put in large amounts. 
<<12:42>> *42* Then one poor widow came and put in two small copper coins, which amounted to a small fraction of a denarius.

<<12:43>> *43* Jesus called His disciples to Him and said, “Truly I tell you, this poor widow has put more than all the others into the treasury. 
<<12:44>> *44* For they all contributed out of their surplus, but she out of her poverty has put in all she had to live on.”

** Mark 13
*** Temple Destruction and Other Signs (Matthew 24:1--8; Luke 21:5--9)
[[html-class:drop][13]]

<<13:1>> As Jesus was leaving the temple, one of His disciples said to Him, “Teacher, look at the magnificent stones and buildings!”

<<13:2>> *2* “Do you see all these great buildings?” Jesus replied. “Not one stone here will be left on another; every one will be thrown down.”

<<13:3>> *3* While Jesus was sitting on the Mount of Olives opposite the temple, Peter, James, John, and Andrew asked Him privately,
<<13:4>> *4* “Tell us, when will these things happen? And what will be the sign that they are about to be fulfilled?”

<<13:5>> *5* Jesus began by telling them, “See to it that no one deceives you. 
<<13:6>> *6* Many will come in My name, claiming, ‘I am He,' and will deceive many. 
<<13:7>> *7* When you hear of wars and rumors of wars, do not be alarmed. These things must happen, but the end is still to come. 
<<13:8>> *8* Nation will rise against nation, and kingdom against kingdom. There will be earthquakes in various places, as well as famines. These are the beginning of birth pains.

*** Witnessing to All Nations (Matthew 24:9--14; Luke 21:10--19)

<<13:9>> *9* So be on your guard. You will be delivered over to the councils and beaten in the synagogues. On My account you will stand before governors and kings as witnesses to them. 
<<13:10>> *10* And the gospel must first be proclaimed to all the nations. 
<<13:11>> *11* But when they arrest you and hand you over, do not worry beforehand what to say. Instead, speak whatever you are given at that time, for it will not be you speaking, but the Holy Spirit.

<<13:12>> *12* Brother will betray brother to death, and a father his child. Children will rise against their parents and have them put to death. 
<<13:13>> *13* You will be hated by everyone because of My name, but the one who perseveres to the end will be saved.

*** The Abomination of Desolation (Matthew 24:15--25; Luke 21:20--24)

<<13:14>> *14* So when you see the abomination of desolation standing where it should not be (let the reader understand), then let those who are in Judea flee to the mountains. 
<<13:15>> *15* Let no one on the housetop go back inside to retrieve anything from his house. 
<<13:16>> *16* And let no one in the field return for his cloak.

<<13:17>> *17* How miserable those days will be for pregnant and nursing mothers! 
<<13:18>> *18* Pray that this will not occur in the winter. 
<<13:19>> *19* For those will be days of tribulation unmatched from the beginning of God's creation until now, and never to be seen again. 
<<13:20>> *20* If the Lord had not cut short those days, nobody would be saved. But for the sake of the elect, whom He has chosen, He has cut them short.

<<13:21>> *21* At that time if anyone says to you, ‘Look, here is the Christ!' or ‘There He is!' do not believe it. 
<<13:22>> *22* For false Christs and false prophets will appear and perform signs and wonders that would deceive even the elect, if that were possible. 
<<13:23>> *23* So be on your guard; I have told you everything in advance.

*** The Return of the Son of Man (Matthew 24:26--31; Luke 21:25--28)

<<13:24>> *24* But in those days, after that tribulation:

‘The sun will be darkened,

and the moon will not give its light;

<<13:25>> *25* the stars will fall from the sky,

and the powers of the heavens will be shaken.'

<<13:26>> *26* At that time they will see the Son of Man coming in the clouds with great power and glory. 
<<13:27>> *27* And He will send out the angels to gather His elect from the four winds, from the ends of the earth to the ends of heaven.

*** The Lesson of the Fig Tree (Matthew 24:32--35; Luke 21:29--33)

<<13:28>> *28* Now learn this lesson from the fig tree: As soon as its branches become tender and sprout leaves, you know that summer is near. 
<<13:29>> *29* So also, when you see these things happening, know that He is near, right at the door. 
<<13:30>> *30* Truly I tell you, this generation will not pass away until all these things have happened. 
<<13:31>> *31* Heaven and earth will pass away, but My words will never pass away.

*** Readiness at Any Hour (Matthew 24:36--51; Luke 12:35--48)

<<13:32>> *32* No one knows about that day or hour, not even the angels in heaven, nor the Son, but only the Father. 
<<13:33>> *33* Be on your guard and stay alert! For you do not know when the appointed time will come.

<<13:34>> *34* It is like a man going on a journey who left his house, put each servant in charge of his own task, and instructed the doorkeeper to keep watch. 
<<13:35>> *35* Therefore keep watch, because you do not know when the master of the house will return---whether in the evening, at midnight, when the rooster crows, or in the morning. 
<<13:36>> *36* Otherwise, he may arrive without notice and find you sleeping. 
<<13:37>> *37* And what I say to you, I say to everyone: Keep watch!”

** Mark 14
*** The Plot to Kill Jesus (Luke 22:1--2; John 11:45--57)
[[html-class:drop][14]]

<<14:1>> Now the Passover and the Feast of Unleavened Bread were two days away, and the chief priests and scribes were looking for a covert way to arrest Jesus and kill Him.
<<14:2>> *2* “But not during the feast,” they said, “or there may be a riot among the people.”

*** Jesus Anointed at Bethany (Luke 7:36--50; John 12:1--8)

<<14:3>> *3* While Jesus was in Bethany reclining at the table in the home of Simon the Leper, a woman came with an alabaster jar of expensive perfume, made of pure nard. She broke open the jar and poured it on Jesus' head.

<<14:4>> *4* Some of those present, however, expressed their indignation to one another: “Why this waste of perfume? 
<<14:5>> *5* It could have been sold for over three hundred denarii and the money given to the poor.” And they scolded her.

<<14:6>> *6* But Jesus said, “Leave her alone; why are you bothering her? She has done a beautiful deed to Me. 
<<14:7>> *7* The poor you will always have with you, and you can help them whenever you want. But you will not always have Me. 
<<14:8>> *8* She has done what she could to anoint My body in advance of My burial. 
<<14:9>> *9* And truly I tell you, wherever the gospel is preached in all the world, what she has done will also be told in memory of her.”

*** Judas Agrees to Betray Jesus (Matthew 26:14--16; Luke 22:3--6)

<<14:10>> *10* Then Judas Iscariot, one of the Twelve, went to the chief priests to betray Jesus to them. 
<<14:11>> *11* They were delighted to hear this, and they promised to give him money.

*** So Judas began to look for an opportunity to betray Jesus.

*** Preparing the Passover (Matthew 26:17--19; Luke 22:7--13)

<<14:12>> *12* On the first day of the Feast of Unleavened Bread, when the Passover lamb was to be sacrificed, Jesus' disciples asked Him, “Where do You want us to prepare for You to eat the Passover?”

<<14:13>> *13* So He sent two of His disciples and told them, “Go into the city, and a man carrying a jug of water will meet you. Follow him, 
<<14:14>> *14* and whichever house he enters, say to the owner, ‘The Teacher asks: Where is My guest room, where I may eat the Passover with My disciples?' 
<<14:15>> *15* And he will show you a large upper room, furnished and ready. Make preparations for us there.”

<<14:16>> *16* So the disciples left and went into the city, where they found everything as Jesus had described. And they prepared the Passover.

*** The Last Supper (Luke 22:14--23; 1 Corinthians 11:17--34)

<<14:17>> *17* When evening came, Jesus arrived with the Twelve. 
<<14:18>> *18* And while they were reclining and eating, Jesus said, “Truly I tell you, one of you who is eating with Me will betray Me.”

<<14:19>> *19* They began to be grieved and to ask Him one after another, “Surely not I?”

<<14:20>> *20* He answered, “It is one of the Twelve---the one who is dipping his hand into the bowl with Me. 
<<14:21>> *21* The Son of Man will go just as it is written about Him, but woe to that man by whom He is betrayed! It would be better for him if he had not been born.”

<<14:22>> *22* While they were eating, Jesus took bread, spoke a blessing and broke it, and gave it to the disciples, saying, “Take it; this is My body.”

<<14:23>> *23* Then He took the cup, gave thanks, and gave it to them, and they all drank from it. 
<<14:24>> *24* He said to them, “This is My blood of the covenant, which is poured out for many. 
<<14:25>> *25* Truly I tell you, I will no longer drink of the fruit of the vine until that day when I drink it anew in the kingdom of God.”

<<14:26>> *26* And when they had sung a hymn, they went out to the Mount of Olives.

*** Jesus Predicts Peter's Denial (Luke 22:31--38; John 13:36--38)

<<14:27>> *27* Then Jesus said to them, “You will all fall away, for it is written:

‘I will strike the Shepherd,

and the sheep will be scattered.'

<<14:28>> *28* But after I have risen, I will go ahead of you into Galilee.”

<<14:29>> *29* Peter declared, “Even if all fall away, I never will.”

<<14:30>> *30* “Truly I tell you,” Jesus replied, “this very night, before the rooster crows twice, you will deny Me three times.”

<<14:31>> *31* But Peter kept insisting, “Even if I have to die with You, I will never deny You.” And all the others said the same thing.

*** Jesus Prays at Gethsemane (Matthew 26:36--46; Luke 22:39--46)

<<14:32>> *32* Then they came to a place called Gethsemane, and Jesus told His disciples, “Sit here while I pray.”

<<14:33>> *33* He took with Him Peter, James, and John, and began to be deeply troubled and distressed. 
<<14:34>> *34* Then He said to them, “My soul is consumed with sorrow to the point of death. Stay here and keep watch.”

<<14:35>> *35* Going a little farther, He fell to the ground and prayed that, if it were possible, the hour would pass from Him.
<<14:36>> *36* “Abba, Father,” He said, “all things are possible for You. Take this cup from Me. Yet not what I will, but what You will.”

<<14:37>> *37* Then Jesus returned and found them sleeping. “Simon, are you asleep?” He asked. “Were you not able to keep watch for one hour? 
<<14:38>> *38* Watch and pray so that you will not enter into temptation. For the spirit is willing, but the body is weak.”

<<14:39>> *39* Again He went away and prayed, saying the same thing. 
<<14:40>> *40* And again Jesus returned and found them sleeping---for their eyes were heavy. And they did not know what to answer Him.

<<14:41>> *41* When Jesus returned the third time, He said, “Are you still sleeping and resting? That is enough! The hour has come. Look, the Son of Man is betrayed into the hands of sinners. 
<<14:42>> *42* Rise, let us go. See, My betrayer is approaching!”

*** The Betrayal of Jesus (Luke 22:47--53; John 18:1--14)

<<14:43>> *43* While Jesus was still speaking, Judas, one of the Twelve, arrived, accompanied by a crowd armed with swords and clubs, sent from the chief priests, scribes, and elders.

<<14:44>> *44* Now the betrayer had arranged a signal with them: “The One I kiss is the man; arrest Him and lead Him away securely.” 
<<14:45>> *45* Going directly to Jesus, he said, “Rabbi!” and kissed Him.

<<14:46>> *46* Then the men seized Jesus and arrested Him. 
<<14:47>> *47* And one of the bystanders drew his sword and struck the servant of the high priest, cutting off his ear.

<<14:48>> *48* Jesus asked the crowd, “Have you come out with swords and clubs to arrest Me as you would an outlaw? 
<<14:49>> *49* Every day I was with you, teaching in the temple courts, and you did not arrest Me. But this has happened that the Scriptures would be fulfilled.”

<<14:50>> *50* Then everyone deserted Him and fled. 
<<14:51>> *51* One young man who had been following Jesus was wearing a linen cloth around his body. They caught hold of him, 
<<14:52>> *52* but he pulled free of the linen cloth and ran away naked.

*** Jesus before the Sanhedrin (Luke 22:66--71; John 18:19--24)

<<14:53>> *53* They led Jesus away to the high priest, and all the chief priests, elders, and scribes assembled. 
<<14:54>> *54* Peter followed Him at a distance, right into the courtyard of the high priest. And he sat with the officers and warmed himself by the fire.

<<14:55>> *55* Now the chief priests and the whole Sanhedrin were seeking testimony against Jesus to put Him to death, but they did not find any. 
<<14:56>> *56* For many bore false witness against Jesus, but their testimony was inconsistent.

<<14:57>> *57* Then some men stood up and testified falsely against Him:
<<14:58>> *58* “We heard Him say, ‘I will destroy this man-made temple, and in three days I will build another that is made without hands.' ” 
<<14:59>> *59* But even their testimony was inconsistent.

<<14:60>> *60* So the high priest stood up before them and questioned Jesus, “Have You no answer? What are these men testifying against You?”

<<14:61>> *61* But Jesus remained silent and made no reply.

Again the high priest questioned Him, “Are You the Christ, the Son of the Blessed One?”

<<14:62>> *62* “I am,” said Jesus, “and you will see the Son of Man sitting at the right hand of Power and coming with the clouds of heaven.”

<<14:63>> *63* At this, the high priest tore his clothes and declared, “Why do we need any more witnesses? 
<<14:64>> *64* You have heard the blasphemy. What is your verdict?”

And they all condemned Him as deserving of death.

<<14:65>> *65* Then some of them began to spit on Him. They blindfolded Him, struck Him with their fists, and said to Him, “Prophesy!” And the officers received Him with slaps in His face.

*** Peter Denies Jesus (Luke 22:54--62; John 18:15--18)

<<14:66>> *66* While Peter was in the courtyard below, one of the servant girls of the high priest came down 
<<14:67>> *67* and saw him warming himself there. She looked at Peter and said, “You also were with Jesus the Nazarene.”

<<14:68>> *68* But he denied it. “I do not know or even understand what you are talking about,” he said. Then he went out to the gateway, and the rooster crowed.

<<14:69>> *69* There the servant girl saw him and again said to those standing nearby, “This man is one of them.”

<<14:70>> *70* But he denied it again.

After a little while, those standing nearby said once more to Peter, “Surely you are one of them, for you too are a Galilean.”

<<14:71>> *71* But he began to curse and swear, “I do not know this man of whom you speak!” 
<<14:72>> *72* And immediately the rooster crowed a second time.

Then Peter remembered the word that Jesus had spoken to him: “Before the rooster crows twice, you will deny Me three times.” And he broke down and wept.

** Mark 15
*** Jesus Delivered to Pilate (Matthew 27:1--2)
[[html-class:drop][15]]

<<15:1>> Early in the morning, the chief priests, elders, scribes, and the whole Sanhedrin devised a plan. They bound Jesus, led Him away, and handed Him over to Pilate.

<<15:2>> *2* So Pilate questioned Him, “Are You the King of the Jews?”

“You have said so,” Jesus replied.

<<15:3>> *3* And the chief priests began to accuse Him of many things.

<<15:4>> *4* Then Pilate questioned Him again, “Have You no answer? Look how many charges they are bringing against You!”

<<15:5>> *5* But to Pilate's amazement, Jesus made no further reply.

*** The Crowd Chooses Barabbas (Matthew 27:15--23; Luke 23:13--25)

<<15:6>> *6* Now it was Pilate's custom at the feast to release to the people a prisoner of their choosing. 
<<15:7>> *7* And a man named Barabbas was imprisoned with the rebels who had committed murder during the insurrection. 
<<15:8>> *8* So the crowd went up and began asking Pilate to keep his custom.

<<15:9>> *9* “Do you want me to release to you the King of the Jews?” Pilate asked. 
<<15:10>> *10* For he knew it was out of envy that the chief priests had handed Jesus over.

<<15:11>> *11* But the chief priests stirred up the crowd to have him release Barabbas to them instead.

*** Pilate Delivers Up Jesus (Matthew 27:24--26)

<<15:12>> *12* So Pilate asked them again, “What then do you want me to do with the One you call the King of the Jews?”

<<15:13>> *13* And they shouted back, “Crucify Him!”

<<15:14>> *14* “Why?” asked Pilate. “What evil has He done?”

*** But they shouted all the louder, “Crucify Him!”

<<15:15>> *15* And wishing to satisfy the crowd, Pilate released Barabbas to them. But he had Jesus flogged, and handed Him over to be crucified.

*** The Soldiers Mock Jesus (Luke 22:63--65; John 19:1--15)

<<15:16>> *16* Then the soldiers led Jesus away into the palace (that is, the Praetorium) and called the whole company together. 
<<15:17>> *17* They dressed Him in a purple robe, twisted together a crown of thorns, and set it on His head. 
<<15:18>> *18* And they began to salute Him: “Hail, King of the Jews!”

<<15:19>> *19* They kept striking His head with a staff and spitting on Him. And they knelt down and bowed before Him. 
<<15:20>> *20* After they had mocked Him, they removed the purple robe and put His own clothes back on Him. Then they led Him out to crucify Him.

*** The Crucifixion (Luke 23:26--43; John 19:16--27)

<<15:21>> *21* Now Simon of Cyrene, the father of Alexander and Rufus, was passing by on his way in from the country, and the soldiers forced him to carry the cross of Jesus.

<<15:22>> *22* They brought Jesus to a place called Golgotha, which means The Place of the Skull. 
<<15:23>> *23* There they offered Him wine mixed with myrrh, but He did not take it.

<<15:24>> *24* And they crucified Him.

They also divided His garments by casting lots to decide what each of them would take.

<<15:25>> *25* It was the third hour when they crucified Him. 
<<15:26>> *26* And the charge inscribed against Him read:

*** THE KING OF THE JEWS.

<<15:27>> *27* Along with Jesus, they crucified two robbers, one on His right and one on His left.

<<15:29>> *29* And those who passed by heaped abuse on Him, shaking their heads and saying, “Aha! You who are going to destroy the temple and rebuild it in three days, 
<<15:30>> *30* come down from the cross and save Yourself!”

<<15:31>> *31* In the same way, the chief priests and scribes mocked Him among themselves, saying, “He saved others, but He cannot save Himself! 
<<15:32>> *32* Let the Christ, the King of Israel, come down now from the cross, so that we may see and believe!” And even those who were crucified with Him berated Him.

*** The Death of Jesus (Luke 23:44--49; John 19:28--30)

<<15:33>> *33* From the sixth hour until the ninth hour darkness came over all the land. 
<<15:34>> *34* At the ninth hour, Jesus cried out in a loud voice, “Eloi, Eloi, lema sabachthani?” which means, “My God, My God, why have You forsaken Me?”

<<15:35>> *35* When some of those standing nearby heard this, they said, “Behold, He is calling Elijah.”

<<15:36>> *36* And someone ran and filled a sponge with sour wine. He put it on a reed and held it up for Jesus to drink, saying, “Leave Him alone. Let us see if Elijah comes to take Him down.”

<<15:37>> *37* But Jesus let out a loud cry and breathed His last. 
<<15:38>> *38* And the veil of the temple was torn in two from top to bottom.

<<15:39>> *39* When the centurion standing there in front of Jesus saw how He had breathed His last, he said, “Truly this man was the Son of God!”

<<15:40>> *40* And there were also women watching from a distance. Among them were Mary Magdalene, Mary the mother of James the younger and of Joses, and Salome. 
<<15:41>> *41* These women had followed Jesus and ministered to Him while He was in Galilee, and there were many other women who had come up to Jerusalem with Him.

*** The Burial of Jesus (Luke 23:50--56; John 19:38--42)

<<15:42>> *42* Now it was already evening. Since it was Preparation Day (that is, the day before the Sabbath), 
<<15:43>> *43* Joseph of Arimathea, a prominent Council member who himself was waiting for the kingdom of God, boldly went to Pilate to ask for the body of Jesus.

<<15:44>> *44* Pilate was surprised to hear that Jesus was already dead, so he summoned the centurion to ask if this was so. 
<<15:45>> *45* When Pilate had confirmed it with the centurion, he granted the body to Joseph.

<<15:46>> *46* So Joseph bought a linen cloth, took down the body of Jesus, wrapped it in the cloth, and placed it in a tomb that had been cut out of the rock. Then he rolled a stone against the entrance to the tomb. 
<<15:47>> *47* Mary Magdalene and Mary the mother of Joseph saw where His body was placed.

** Mark 16
*** The Resurrection (Luke 24:1--12; John 20:1--9)
[[html-class:drop][16]]

<<16:1>> When the Sabbath was over, Mary Magdalene, Mary the mother of James, and Salome bought spices so they could go and anoint the body of Jesus. 
<<16:2>> *2* Very early on the first day of the week, just after sunrise, they went to the tomb. 
<<16:3>> *3* They were asking one another, “Who will roll away the stone from the entrance of the tomb?” 
<<16:4>> *4* But when they looked up, they saw that the stone had been rolled away, even though it was extremely large.

<<16:5>> *5* When they entered the tomb, they saw a young man dressed in a white robe sitting on the right side, and they were alarmed. 
<<16:6>> *6* But he said to them, “Do not be alarmed. You are looking for Jesus the Nazarene, who was crucified. He has risen! He is not here! See the place where they put Him. 
<<16:7>> *7* But go, tell His disciples and Peter, ‘He is going ahead of you into Galilee. There you will see Him, just as He told you.' ”

<<16:8>> *8* So the women left the tomb and ran away, trembling and bewildered. And in their fear they did not say a word to anyone.

*** Jesus Appears to Mary Magdalene (John 20:10--18)

<<16:9>> *9* Early on the first day of the week, after Jesus had risen, He appeared first to Mary Magdalene, from whom He had driven out seven demons. 
<<16:10>> *10* She went and told those who had been with Him, who were mourning and weeping. 
<<16:11>> *11* And when they heard that Jesus was alive and she had seen Him, they did not believe it.

*** Jesus Appears to Two Disciples (Luke 24:13--35)

<<16:12>> *12* After this, Jesus appeared in a different form to two of them as they walked along in the country.

<<16:13>> *13* And they went back and reported it to the rest, but they did not believe them either.

*** The Great Commission (Matthew 28:16--20)

<<16:14>> *14* Later, as they were eating, Jesus appeared to the Eleven and rebuked them for their unbelief and hardness of heart, because they did not believe those who had seen Him after He had risen.

<<16:15>> *15* And He said to them, “Go into all the world and preach the gospel to every creature. 
<<16:16>> *16* Whoever believes and is baptized will be saved, but whoever does not believe will be condemned. 
<<16:17>> *17* And these signs will accompany those who believe: In My name they will drive out demons; they will speak in new tongues; 
<<16:18>> *18* they will pick up snakes with their hands, and if they drink any deadly poison, it will not harm them; they will lay their hands on the sick, and they will be made well.”

*** The Ascension (Luke 24:50--53; Acts 1:6--11)

<<16:19>> *19* After the Lord Jesus had spoken to them, He was taken up into heaven and sat down at the right hand of God.

<<16:20>> *20* And they went out and preached everywhere, and the Lord worked through them, confirming His word by the signs that accompanied it.

